#!/bin/sh
# =============================================================================
# OLLAMA SETUP INFO PRINTER
# Prints URLs, upload steps, model guide, VS Code setup, and Make commands.
# =============================================================================

sleep 5

PRIMARY_MODEL="${PRIMARY_MODEL:-devstral:24b}"
RESEARCH_MODEL="${RESEARCH_MODEL:-deepseek-r1:14b}"
FALLBACK_MODEL="${FALLBACK_MODEL:-qwen2.5-coder:7b}"
EMBEDDING_MODEL="${EMBEDDING_MODEL:-nomic-embed-text}"
WEBUI_PORT="${WEBUI_PORT:-3000}"
OLLAMA_PORT="${OLLAMA_PORT:-11434}"

echo ""
echo "=============================================================================="
echo "  OLLAMA ULTIMATE STACK — READY"
echo "=============================================================================="
echo ""
echo "100% local. Zero API keys. Zero subscription. Models stay on this machine."
echo ""
echo "------------------------------------------------------------------------------"
echo "  ACCESS"
echo "------------------------------------------------------------------------------"
echo "  WebUI (chat, files, RAG, history):  http://localhost:${WEBUI_PORT}"
echo "  Ollama API:                         http://localhost:${OLLAMA_PORT}"
echo "  OpenAI-compatible:                  http://localhost:${OLLAMA_PORT}/v1"
echo ""
echo "------------------------------------------------------------------------------"
echo "  FILE UPLOAD + DOCUMENT CHAT"
echo "------------------------------------------------------------------------------"
echo "  1. Open http://localhost:${WEBUI_PORT}"
echo "  2. Click + / paperclip under the chat box"
echo "  3. Upload PDF, Word, text, code, or images"
echo "  4. Ask: Summarize this document"
echo ""
echo "  Folder mounts (AI can read these paths):"
echo "    ./projects  ->  /projects"
echo "    ./uploads   ->  /uploads"
echo ""
echo "------------------------------------------------------------------------------"
echo "  MODEL GUIDE"
echo "------------------------------------------------------------------------------"
echo "  ${PRIMARY_MODEL}     coding, bug fixes, generation"
echo "  ${RESEARCH_MODEL}    research, reasoning, math, analysis"
echo "  ${FALLBACK_MODEL}    fast replies and autocomplete"
echo "  ${EMBEDDING_MODEL}   RAG / document search (not a chat model)"
echo ""
echo "  Switch models anytime with the WebUI dropdown."
echo ""
echo "------------------------------------------------------------------------------"
echo "  VS CODE / CONTINUE"
echo "------------------------------------------------------------------------------"
echo "  1. Install the Continue extension"
echo "  2. Command Palette -> Continue: Open Config.json"
echo "  3. Paste continue-config.json from this repo"
echo "  4. Ctrl+L (Cmd+L) to chat; highlight code and click Apply"
echo ""
echo "  Provider: Ollama"
echo "  API URL:  http://localhost:${OLLAMA_PORT}"
echo "  Model:    ${PRIMARY_MODEL}"
echo ""
echo "------------------------------------------------------------------------------"
echo "  MAKE COMMANDS"
echo "------------------------------------------------------------------------------"
echo "  make up              Start the stack"
echo "  make down            Stop the stack"
echo "  make chat            Terminal chat (coding model)"
echo "  make chat-research   Terminal chat (research model)"
echo "  make chat-fast       Terminal chat (fast model)"
echo "  make models          List installed models"
echo "  make ps              Show running models"
echo "  make status          Compose service status"
echo "  make logs            Ollama logs"
echo "  make webui-logs      WebUI logs"
echo "  make pull-coding     Update coding model"
echo "  make pull-research   Update research model"
echo "  make pull-all        Update all chat + embedding models"
echo "  make update          Pull git + images, recreate containers"
echo "  make clean           Prune unused Docker data (keeps models)"
echo "  make nuke            Delete ALL models and chat history"
echo "  make info            Print this summary"
echo "  make help            List Make targets"
echo ""
echo "  Windows (no Make):   .\\install.ps1   .\\update.ps1"
echo ""
echo "  Need help installing? Contact barrelaxman@gmail.com for remote setup services."
echo "=============================================================================="
echo ""
